'use strict';
const $=id=>document.getElementById(id);
let showArchive=false;
let current=null, dirty=false, saving=null, autoTimer=null, articles=[], job={}, lastVersion=-1, lastMessage='', ready=false;
async function call(action,data={}){const response=await window.pywebview.api.dispatch(action,data);if(!response.ok)throw new Error(response.error);return response.data;}
function notify(message,error=false){$('status').textContent=message;$('status').classList.toggle('error',error);}
function backup(){if(current)localStorage.setItem('draft:'+current.id+':'+current.mode,JSON.stringify({text:$('editor').value,revision:current.revision}));}
function renderList(){const search=$('search').value.toLowerCase();$('articles').replaceChildren();for(const article of articles.filter(a=>a.title.toLowerCase().includes(search))){const button=document.createElement('button');button.className='article-item'+(current?.id===article.id?' active':'');button.textContent=article.title;const detail=document.createElement('small');detail.textContent=(article.draft?'초안':'공개 대상')+' · '+article.date;button.append(detail);button.onclick=()=>perform(()=>select(article.id));$('articles').append(button);}$('count').textContent=articles.length;}
async function reloadList(){articles=(await call('list')).articles;renderList();}
function display(doc){current=doc;dirty=false;$('editor').value=doc.text;$('title').textContent=doc.metadata.title||doc.id;$('draft-badge').textContent=doc.metadata.draft?'초안':'공개 대상';$('file-label').textContent=doc.mode==='notes'?'비공개 로컬 메모':doc.mode==='references'?'BibTeX 참고문헌':'Markdown / Quarto';$('save-state').textContent='저장됨';document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('selected',b.dataset.mode===doc.mode));$('word-count').textContent=doc.text.length.toLocaleString()+'자';localStorage.setItem('lastArticle',doc.id);renderList();}
async function select(id,mode='article'){await saveNow();showArchive=false;display(await call('read',{id,mode}));const cached=localStorage.getItem('draft:'+id+':'+mode);if(cached){try{const draft=JSON.parse(cached);if(draft.text!==current.text&&draft.revision===current.revision){$('editor').value=draft.text;changed();notify('마지막 편집 내용을 복구했습니다.');}}catch{}}if(mode==='article')await beginPreview();}
async function saveNow(){clearTimeout(autoTimer);if(saving){await saving;if(dirty)return saveNow();return;}if(!current||!dirty)return;const capture={id:current.id,mode:current.mode,text:$('editor').value,revision:current.revision};$('save-state').textContent='저장 중…';saving=(async()=>{const result=await call('save',capture);current.revision=result.revision;current.text=capture.text;dirty=$('editor').value!==capture.text;$('save-state').textContent=dirty?'편집 중':'저장됨';if(!dirty)localStorage.removeItem('draft:'+capture.id+':'+capture.mode);else backup();})().catch(error=>{$('save-state').textContent='저장 실패';notify(error.message,true);throw error;}).finally(()=>{saving=null;});await saving;}
function changed(){dirty=true;backup();call('draft',window.draftState()).catch(error=>notify(error.message,true));$('save-state').textContent='편집 중';$('word-count').textContent=$('editor').value.length.toLocaleString()+'자';clearTimeout(autoTimer);autoTimer=setTimeout(()=>perform(async()=>{await saveNow();if(current.mode==='article')await beginPreview();}),1100);}
async function beginPreview(){if(!current)return;if(job.busy&&job.kind!=='preview')return;await call('preview',{id:current.id});}
async function perform(fn){try{await fn();}catch(error){notify(error.message,true);}}
function insert(text){if(!current)return;const editor=$('editor');editor.setRangeText(text,editor.selectionStart,editor.selectionEnd,'end');editor.focus();changed();}
const inserts={heading:'\n## 제목\n',bold:'**강조할 내용**',math:'\n$$\nY = XW\n$$ {#eq-projection}\n',code:'\n```python\n# 구현 코드\n```\n',diagram:'\n```{mermaid}\nflowchart LR\n    X[입력] --> M[핵심 모듈]\n    M --> Y[출력]\n```\n',citation:'[@citation-key]'};
async function poll(){try{const state=await call('status');const finished=job.busy&&!state.busy;job=state;$('busy-dot').classList.toggle('running',state.busy);$('cancel').hidden=!state.busy;$('auth-code').textContent=state.code||'';$('editor').disabled=state.busy&&state.kind==='publish';document.querySelectorAll('[data-action="publish"],[data-action="new"],[data-action="metadata"],[data-action="login"]').forEach(b=>b.disabled=state.busy);if(state.message!==lastMessage){notify(state.message,state.error);lastMessage=state.message;}if(state.version!==lastVersion&&state.url&&state.url.includes('/'+current?.id+'/')){lastVersion=state.version;$('preview').src=(showArchive?'/preview/index.html':state.url)+'?v='+state.version;$('preview').classList.add('visible');$('preview-empty').style.display='none';}if($('logs-dialog').open)$('logs').textContent=state.logs;if(finished&&state.kind==='publish'&&current){display(await call('read',{id:current.id,mode:current.mode}));await reloadList();} }catch(error){notify(error.message,true);} }
async function action(name){if(name==='archive'){await saveNow();showArchive=true;$('preview').src='/preview/index.html?v='+Date.now();$('preview').classList.add('visible');$('preview-empty').style.display='none';await beginPreview();return;}if(name==='new'){$('new-dialog').showModal();return;}if(name==='save'){await saveNow();notify('저장했습니다.');if(current?.mode==='article')await beginPreview();return;}if(name==='preview'){await saveNow();await beginPreview();return;}if(name==='metadata'){if(!current)return;await saveNow();const doc=await call('read',{id:current.id});const form=$('metadata-form');form.elements.title.value=doc.metadata.title||'';form.elements.description.value=doc.metadata.description||'';form.elements.categories.value=(doc.metadata.categories||[]).join(', ');form.elements.draft.checked=!!doc.metadata.draft;$('metadata-dialog').showModal();return;}if(name==='image'){if(current?.mode!=='article')throw new Error('본문 탭에서 이미지를 넣으세요.');const result=await call('image',{id:current.id});if(!result.cancelled)insert(result.markdown);return;}if(name==='publish'){if(!current)return;await saveNow();await call('publish',{id:current.id});return;}if(name==='login'){await call('login');return;}if(name==='stop'){notify((await call('stop')).message);return;}if(name==='site'||name==='deployment'){await call('open',{target:name});return;}if(name==='logs'){$('logs').textContent=(await call('status')).logs;$('logs-dialog').showModal();}}
document.querySelectorAll('[data-action]').forEach(button=>button.onclick=()=>perform(()=>action(button.dataset.action)));
document.querySelectorAll('[data-insert]').forEach(button=>button.onclick=()=>insert(inserts[button.dataset.insert]));
document.querySelectorAll('[data-close]').forEach(button=>button.onclick=()=>button.closest('dialog').close());
document.querySelectorAll('[data-mode]').forEach(button=>button.onclick=()=>perform(()=>current&&select(current.id,button.dataset.mode)));
$('search').oninput=renderList;$('editor').oninput=changed;
$('editor').onkeydown=event=>{if(event.key==='Tab'){event.preventDefault();insert('    ');}};
document.addEventListener('keydown',event=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='s'){event.preventDefault();perform(()=>action('save'));}});
$('desktop').onclick=()=>{$('preview').classList.remove('mobile');$('desktop').classList.add('selected');$('mobile').classList.remove('selected');};
$('mobile').onclick=()=>{$('preview').classList.add('mobile');$('mobile').classList.add('selected');$('desktop').classList.remove('selected');};
$('new-form').onsubmit=event=>{event.preventDefault();perform(async()=>{const data=new FormData(event.target);await saveNow();const doc=await call('create',{title:data.get('title'),slug:data.get('slug')});$('new-dialog').close();event.target.reset();await reloadList();display(doc);await beginPreview();});};
$('metadata-form').onsubmit=event=>{event.preventDefault();perform(async()=>{await saveNow();const form=event.target;const doc=await call('metadata',{id:current.id,title:form.elements.title.value,description:form.elements.description.value,categories:form.elements.categories.value.split(',').map(x=>x.trim()).filter(Boolean),draft:form.elements.draft.checked});$('metadata-dialog').close();display(doc);await reloadList();await beginPreview();});};
$('publish-confirm').onclick=()=>perform(async()=>{await saveNow();$('publish-dialog').close();await call('publish',{id:current.id});});
window.draftState=()=>current?{id:current.id,mode:current.mode,text:$('editor').value,revision:current.revision,dirty}:null;
window.addEventListener('pywebviewready',()=>perform(async()=>{await reloadList();const preferred=localStorage.getItem('lastArticle');const id=articles.find(a=>a.id===preferred)?.id||articles.find(a=>a.id==='first-review')?.id||articles[0]?.id;if(id)await select(id);window.appReady=true;setInterval(poll,600);await poll();}));
